version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 2
    target-branch: "develop"
    schedule:
      interval: "daily"
    reviewers:
      - "ojaha065"